helm/_global/idpay-onboarding-workflow.yaml, helm/dev/top/idpay-onboarding-workflow/Chart.yaml, helm/dev/top/idpay-onboarding-workflow/values.yaml
=> fix: IDP-2716 parameters for idpay-onboarding-workflow

helm/_global/idpay-admissibility-assessor.yaml, helm/_global/idpay-group.yaml, helm/_global/idpay-iban.yaml, helm/_global/idpay-initiative-statistics.yaml, helm/_global/idpay-merchant.yaml, helm/_global/idpay-notification-email.yaml, helm/_global/idpay-notification-manager.yaml, helm/_global/idpay-onboarding-workflow.yaml, helm/_global/idpay-payment-instrument.yaml, helm/_global/idpay-payment.yaml, helm/_global/idpay-portal-welfare-backend-initiative.yaml, helm/_global/idpay-portal-welfare-backend-role-permission.yaml, helm/_global/idpay-ranking.yaml, helm/_global/idpay-recovery-error-topic.yaml, helm/_global/idpay-reward-calculator.yaml, helm/_global/idpay-reward-notification.yaml, helm/_global/idpay-reward-user-id-splitter.yaml, helm/_global/idpay-self-expense-backend.yaml, helm/_global/idpay-timeline.yaml, helm/_global/idpay-transactions.yaml, helm/_global/idpay-wallet.yaml
=> fix: [IDP-2666] removed serviceAccount from yaml

helm/_global/idpay-payment-instrument.yaml, helm/_global/idpay-recovery-error-topic.yaml, helm/_global/idpay-reward-calculator.yaml, helm/_global/idpay-reward-user-id-splitter.yaml, helm/_global/idpay-self-expense-backend.yaml, helm/dev/ext/idpay-self-expense-backend/values.yaml
=> fix: yaml update

helm/_global/idpay-onboarding-workflow.yaml, helm/_global/idpay-reward-user-id-splitter.yaml, helm/dev/ext/idpay-iban/values.yaml, helm/dev/ext/idpay-notification-email/values.yaml, helm/dev/ext/idpay-notification-manager/values.yaml, helm/dev/ext/idpay-self-expense-backend/values.yaml, helm/dev/mid/idpay-group/values.yaml, helm/dev/mid/idpay-initiative-statistics/values.yaml, helm/dev/mid/idpay-payment-instrument/values.yaml, helm/dev/mid/idpay-portal-welfare-backend-role-permission/values.yaml, helm/dev/mid/idpay-ranking/values.yaml, helm/dev/mid/idpay-recovery-error-topic/values.yaml, helm/dev/mid/idpay-reward-notification/values.yaml, helm/dev/mid/idpay-reward-user-id-splitter/values.yaml, helm/dev/mid/idpay-timeline/values.yaml, helm/dev/top/idpay-admissibility-assessor/values.yaml, helm/dev/top/idpay-merchant/values.yaml, helm/dev/top/idpay-onboarding-workflow/values.yaml, helm/dev/top/idpay-payment/values.yaml, helm/dev/top/idpay-portal-welfare-backend-initiative/values.yaml, helm/dev/top/idpay-reward-calculator/values.yaml, helm/dev/top/idpay-transactions/values.yaml, helm/dev/top/idpay-wallet/values.yaml
=> chore: tag update

helm/_global/idpay-mock.yaml, helm/dev/ext/idpay-mock/Chart.yaml, helm/dev/ext/idpay-mock/values.yaml
=> chore: [IDP-2737] add idpay mock 

helm/_global/idpay-kafka-connect.yaml, helm/dev/top/idpay-kafka-connect/Chart.yaml, helm/dev/top/idpay-kafka-connect/values.yaml
=> chore: [IDP-2740] idpay kafka connector migration

helm/dev/top/idpay-kafka-connect/values.yaml
=> fix: kafka connect port 

.devops/deploy-argocd-apps.yml, helm/_global/idpay-keycloak.yaml, helm/dev/top/idpay-keycloak/Chart.yaml, helm/dev/top/idpay-keycloak/values.yaml
=> feat: Add keycloak on idpay-deploy-aks

helm/_global/idpay-asset-register-backend.yaml, helm/dev/top/idpay-asset-register-backend/values.yaml
=> chore: [RDB-51] Integrazione servizio eprel

helm/_global/idpay-asset-register-backend.yaml
=> fix: proxyBodySize added

helm/_global/idpay-merchant.yaml, helm/dev/top/idpay-merchant/values.yaml, helm/uat/top/idpay-merchant/values.yaml
Add new envSecret for keycloak admin client connection
=> chore: Add new keycloack envSecret

helm/dev/top/idpay-merchant/values.yaml, helm/prod/top/idpay-merchant/values.yaml, helm/uat/top/idpay-merchant/values.yaml
Add MERCHANT_DEFAULT_INITIATIVES env
=> chore: EBE-90 add env

helm/dev/top/idpay-payment/values.yaml, helm/uat/top/idpay-payment/values.yaml
Changed tag from:
- release-dev -> develop
- release-uat -> uat
=> fix: changed snapshot tag

helm/dev/top/idpay-merchant/values.yaml, helm/prod/top/idpay-merchant/values.yaml, helm/uat/top/idpay-merchant/values.yaml
=> fix: EBE-90 Fix env values

helm/uat/top/idpay-merchant/values.yaml
Add default Initiatives for uat
=> chore: Add default Initiatives for uat

helm/dev/ext/idpay-mock/values.yaml
=> fix: deploy tag idpay-mock

helm/_global/idpay-mock.yaml
- update variables for decrypt user info
=> feat: [UPBE-174] Added pdv variables for idpay-mock

helm/_global/idpay-ranker.yaml
=> fix: Update idpay-ranker.yaml

helm/_global/idpay-wallet.yaml
Added PAYMENT_URI: idpay_payment_host
=> feat: UPBE-190-added PAYMENT_URI: idpay_payment_host

helm/prod/top/idpay-asset-register-backend/values.yaml, helm/uat/top/idpay-asset-register-backend/values.yaml
=> fix: LTBE-23 reduced min e max replica for asset register

.devops/deploy-argocd-apps.yml, .devops/templates/postman-tests-template.yml, helm/dev/top/idpay-asset-register-backend/values.yaml, helm/prod/top/idpay-asset-register-backend/values.yaml, helm/uat/top/idpay-asset-register-backend/values.yaml
=> fix: eie postman test

helm/_global/mcshared-datavault.yaml
=> feat: Added global env. conf. for datavault microservice.

helm/uat/top/idpay-merchant/values.yaml
=> feat: Add default initiative for uat

helm/_global/mcshared-datavault.yaml, helm/dev/top/mcshared-datavault/values.yaml, helm/prod/top/mcshared-datavault/values.yaml, helm/uat/top/mcshared-datavault/values.yaml
=> feat: New version of mcshared-datavault.

helm/dev/top/idpay-admissibility-assessor/values.yaml
=> fix: Upbe 249 adeguamento admissibility per controllo su fine iniziativa post scodatore

helm/_global/mcshared-datavault.yaml, helm/dev/top/mcshared-datavault/values.yaml, helm/prod/top/mcshared-datavault/values.yaml, helm/uat/top/mcshared-datavault/values.yaml
=> feat: Upgraded mcshared-datavault to 1.1.1

helm/_global/mcshared-datavault.yaml, helm/dev/top/mcshared-datavault/values.yaml, helm/prod/top/mcshared-datavault/values.yaml, helm/uat/top/mcshared-datavault/values.yaml
=> feat: Mcshared-datavault updated to 2.0.1.

helm/uat/top/idpay-asset-register-backend/values.yaml
- Update uat yaml for asset register
=> fix: update postman yaml uat

helm/_global/idpay-payment.yaml
=> feat: Add storage config
